import "./globals.css";

export const metadata = {
  title: "Label4Learn",
  description: "Generated by create next app",
  icons: {
    icon: "/graduation-cap.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt">
      <body>{children}</body>
    </html>
  );
}
